services:
  db:
    image: postgres
    container_name: pg_gasAwareness2
    restart: always
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: Password1!
      POSTGRES_DB: gasAwareness2
    ports:
      - "5432:5432"